/*************************************

项目名称：Sex Actions-情侣性爱游戏
下载地址：https://t.cn/A6lB0WCV
版本支持：1.2
更新日期：2024-01-03
脚本作者：chxm1023
电报频道：https://t.me/chxm1023
使用声明：⚠️仅供参考，🈲转载与售卖！

**************************************

[rewrite_local]
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/?(.*?)*$) url script-response-body https://raw.githubusercontent.com/sultan1sa/Revenuecat/main/generation/Revenuecat.js
^https?:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/?(.*?)*$) url script-request-header https://raw.githubusercontent.com/sultan1sa/Revenuecat/main/generation/Revenuecat.js

[mitm]
hostname = api.revenuecat.com

*************************************/
// GENERATED BY SGFRC By D3WXY
let obj = {
    "request_date_ms": 1704664060864,
    "request_date": "2024-01-07T21:47:40Z",
    "subscriber": {
        "non_subscriptions": {},
        "first_seen": "2024-01-07T21:42:02Z",
        // GENERATED BY SGFRC By D3WXY
        "original_application_version": "1",
        "other_purchases": {},
        "management_url": null,
        // GENERATED BY SGFRC By D3WXY
        "subscriptions": {
            "unlock": {
                "ownership_type": "PURCHASED",
                "store": "app_store",
                "is_sandbox": false,
                // GENERATED BY SGFRC By D3WXY
                "expires_date": "2099-03-27T07:52:54Z",
                "original_purchase_date": "2020-03-27T07:52:55Z",
                "purchase_date": "2020-03-27T07:52:54Z"
            },
            "com.tk.client.lifetime": {
                "ownership_type": "PURCHASED",
                "store": "app_store",
                "is_sandbox": false,
                // GENERATED BY SGFRC By D3WXY
                "expires_date": "2099-03-27T07:52:54Z",
                "original_purchase_date": "2020-03-27T07:52:55Z",
                "purchase_date": "2020-03-27T07:52:54Z"
            },
            "rochat_premium_lifetime01": {
                "ownership_type": "PURCHASED",
                "store": "app_store",
                "is_sandbox": false,
                // GENERATED BY SGFRC By D3WXY
                "expires_date": "2099-03-27T07:52:54Z",
                "original_purchase_date": "2020-03-27T07:52:55Z",
                "purchase_date": "2020-03-27T07:52:54Z"
            }
        },
        "entitlements": {
            "com.overdesigned.incognito.lifetime": {
                "ownership_type": "PURCHASED",
                // GENERATED BY SGFRC By D3WXY
                "store": "app_store",
                "is_sandbox": false,
                "expires_date": "2099-03-27T07:52:54Z",
                "original_purchase_date": "2020-03-27T07:52:55Z",
                // GENERATED BY SGFRC By D3WXY
                "purchase_date": "2020-03-27T07:52:54Z",
                "product_identifier": "unlock"
            },
            "pro": {
                "ownership_type": "PURCHASED",
                // GENERATED BY SGFRC By D3WXY
                "store": "app_store",
                "is_sandbox": false,
                "expires_date": "2099-03-27T07:52:54Z",
                "original_purchase_date": "2020-03-27T07:52:55Z",
                // GENERATED BY SGFRC By D3WXY
                "purchase_date": "2020-03-27T07:52:54Z",
                "product_identifier": "com.tk.client.lifetime"
            },
            "premium": {
                "ownership_type": "PURCHASED",
                // GENERATED BY SGFRC By D3WXY
                "store": "app_store",
                "is_sandbox": false,
                "expires_date": "2099-03-27T07:52:54Z",
                "original_purchase_date": "2020-03-27T07:52:55Z",
                // GENERATED BY SGFRC By D3WXY
                "purchase_date": "2020-03-27T07:52:54Z",
                "product_identifier": "rochat_premium_lifetime01"
            }
        },
        "original_purchase_date": "2024-01-07T21:38:41Z",
        // GENERATED BY SGFRC By D3WXY
        "original_app_user_id": "$RCAnonymousID:06923c3f1dfc4f23b1b56c9e24dbdffc",
        "last_seen": "2024-01-07T21:42:02Z"
    }
};
$done({response: {body: JSON.stringify(obj), status: 200}});
// GENERATED BY SGFRC By D3WXY